// Code generated by mockery v1.0.0. DO NOT EDIT.

package nps

import mock "github.com/stretchr/testify/mock"
import time "time"

// mockINote is an autogenerated mock type for the iNote type
type mockINote struct {
	mock.Mock
}

// ContentPath provides a mock function with given fields:
func (_m *mockINote) ContentPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ContentType provides a mock function with given fields:
func (_m *mockINote) ContentType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MTime provides a mock function with given fields:
func (_m *mockINote) MTime() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Path provides a mock function with given fields:
func (_m *mockINote) Path() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Title provides a mock function with given fields:
func (_m *mockINote) Title() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
