// Code generated by mockery v1.0.0. DO NOT EDIT.

package runnote

import mock "github.com/stretchr/testify/mock"

// MockCfg is an autogenerated mock type for the Cfg type
type MockCfg struct {
	mock.Mock
}

// ListContentRunner provides a mock function with given fields: _a0, _a1
func (_m *MockCfg) ListContentRunner(_a0 []string, _a1 string) ([]string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []string
	if rf, ok := ret.Get(0).(func([]string, string) []string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDirRunner provides a mock function with given fields: _a0
func (_m *MockCfg) ListDirRunner(_a0 []string) ([]string, error) {
	ret := _m.Called(_a0)

	var r0 []string
	if rf, ok := ret.Get(0).(func([]string) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
